Server:
  RunMode: debug
  HttpPort: 8083
  ReadTime: 60
  WriteTimeout: 60
  DBtype: mysql
  Username: root
  Password: root
  Host: 127.0.0.1:3306
  DBName: digital
  #  TablePrefix:digital
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
  SeverHost: http://127.0.0.1:8088
  RedisHost: 127.0.0.1:6379
  RedisPassword:

  DbUri: fone:123456@tcp(10.1.5.61:3306)/fone_qa?charset=utf8mb4&parseTime=True&&loc=Asia%2FShanghai
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
